import Navbar from "@/components/ui/navbar";
import "@/app/globals.css";
import Banner from "@/components/ui/banner";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="mx-10 md:mx-32 py-20">
          <Navbar />
          {children}
        </div>
        <div className="fixed bottom-0 w-full">
          <Banner />
        </div>
      </body>
    </html>
  );
}
