import Navbar from "@/components/ui/navbar";
import "@/app/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-10 md:mx-32">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
